# Generated by Django 3.2.7 on 2021-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_Details', '0002_auto_20211222_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Alternative_Email', models.EmailField(max_length=200)),
                ('Mobile_no', models.CharField(max_length=100)),
                ('Alternative_Mobile_no', models.CharField(max_length=100)),
            ],
        ),
    ]
